#!/bin/bash

#######################################
# Suppress bash deprecation warning on osx.
#######################################
export_bash_warning_supression(){
    export BASH_SILENCE_DEPRECATION_WARNING=1
}

#######################################
# Configure bash histoty 
#######################################
export_history_settings(){
    export HISTFILESIZE=1000
    export HISTSIZE=1000
    export HISTTIMEFORMAT="%h %d %H:%M:%S "
}

# history settings apply to all machines
export_history_settings

# export machine specific settings
case $MACHINE in 
    "lanl_macbook")
        export_bash_warning_supression
        ;;
esac
    
# clean up namespace
unset export_LANL_proxy
unset export_history_settings
unset export_bash_warning_supression
