#!/bin/bash

#######################################
# Suppress bash deprecation warning on osx.
#######################################
export_bash_warning_supression(){
    export BASH_SILENCE_DEPRECATION_WARNING=1
}

#######################################
# Configure bash histoty
#######################################
export_history_settings(){
    export HISTFILESIZE=1000
    export HISTSIZE=1000
    export HISTTIMEFORMAT="%h %d %H:%M:%S "
    export HISTIGNORE="history*:!*history*:clear:git status:date"
}


#######################################
# Configure for DoD's HPCMP Kerberos Kit
#######################################
export_HPCMP_Kerberos(){
    export PATH="/usr/local/krb5/bin:/usr/local/ossh/bin:$PATH"
    export KRB5_CONFIG=/etc/krb5.conf
}

# history settings apply to all machines
export_history_settings

# export machine specific settings
case $MACHINE in

    "lanl_macbook")
        export_bash_warning_supression
        export_HPCMP_Kerberos
        ;;

esac

# clean up namespace
unset export_history_settings
unset export_bash_warning_supression
