#!/bin/bash

source ${HOME}/.dotfiles/lib/utils

find_conda_install(){

    CONDA_INSTALL_LOCATION=$(find "$1" -maxdepth 1 -type d -name "miniforge3")
    
    # should probably check is somehow multiple condas are found
    if [[ -z ${CONDA_INSTALL_LOCATION} ]]; then
        e_error "Conda not found"
    fi
}

# export machine specific settings
case $MACHINE in 

    "perlmutter")
        find_conda_install "${HOME}/"
        ;;
    "chicoma")
        find_conda_install "/usr/projects/climate/anolan/"
        ;;
    "chrysalis")
        find_conda_install "${HOME}/"
        ;;
    "cedar")
        # don't look for conda install on cedar
        true
        ;;
    *)
        find_conda_install "${HOME}/"
        ;;
esac

# >>> mamba initialize >>>
# !! Contents within this block are managed by 'mamba shell init' !!
export MAMBA_EXE="${CONDA_INSTALL_LOCATION}/bin/mamba";
export MAMBA_ROOT_PREFIX="${CONDA_INSTALL_LOCATION}";
__mamba_setup="$("$MAMBA_EXE" shell hook --shell bash --root-prefix "$MAMBA_ROOT_PREFIX" 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__mamba_setup"
else
    alias mamba="$MAMBA_EXE"  # Fallback on help from mamba activate
fi
unset __mamba_setup
# <<< mamba initialize <<<

unset find_conda_install
unset CONDA_INSTALL_LOCATION
