" Automatic plugin install on new machines, following:
" https://gist.github.com/miguelgrinberg/527bb5a400791f89b3c4da4bd61222e4
let need_to_install_plugins = 0
if empty(glob('$HOME/.vim/bundle/Vundle.vim'))
    silent !git clone
        \ https://github.com/VundleVim/Vundle.vim.git
        \ $HOME/.vim/bundle/Vundle.vim
    let need_to_install_plugins = 1
endif

" Following from `Vundle` Quick start at:  
" https://github.com/VundleVim/Vundle.vim/blob/master/README.md
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=$HOME/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
" For git branch in vim status line 
Plugin 'tpope/vim-fugitive'
" lean & mean status/tabline for vim that's light as air  
Plugin 'vim-airline/vim-airline'
" A collection of themes for vim-airline 
Plugin 'vim-airline/vim-airline-themes'
" Simple tmux statusline generator with support for powerline symbols
Plugin 'edkolev/tmuxline.vim'
" Easier navigation between tmux panes and vim splits 
Plugin 'christoomey/vim-tmux-navigator'
" Allow LaTeX/unicode characters in vim for julia 
Plugin 'JuliaEditorSupport/julia-vim'
" Onehalf theme
Plugin 'sonph/onehalf', {'rtp': 'vim/'}
" All of your Plugins must be added before the following line
call vundle#end()            " required

" have vim try to recognize file types 
filetype plugin indent on    " required
" turn on syntax highlighting 
syntax on

if need_to_install_plugins == 1
    echo "Installing plugins..."
    silent! PluginInstall
    echo "Done!"
    q
endif


" always show the status bar
set laststatus=2

" show line numbers
set relativenumber
set number 

" highlight matching bracket or brace
set showmatch

" highlight search results
set hlsearch
" highlight incremental searches
set incsearch

" the same indent as the line you're currently on. Useful for READMEs, etc.
set autoindent

" set tab to be 4 spaces for indentation
set expandtab tabstop=4 shiftwidth=4

" Instead of failing a command because of unsaved changes, instead raise a
" dialogue asking if you wish to save changed files.
set confirm

" python specific colorcolumn following PEP8
autocmd FileType python setlocal colorcolumn=80

" enable xml syntax highlighting for streams files
au BufRead,BufNewFile streams.landice,streams.ocean,streams.seaice set filetype=xml

" Set the command window height to 2 lines, to avoid many cases of having to
" press <Enter> to continue"
set cmdheight=2

" sane text files
set fileformat=unix
set encoding=utf-8
set fileencoding=utf-8

" display unprintable characters
"set list

" Use textmate-style whitespace characters
"set listchars=tab:▸\ ,eol:¬

" Set 'nocompatible' to ward off unexpected things that your distro might
" have made, as well as sanely reset options when re-sourcing .vimrc
set nocompatible

" Display the cursor position on the last line of the screen or in the status
" line of a window
set ruler

" Add git branch to statusline
set statusline=%F\ %m\ %{fugitive#statusline()}\ %y%=%l,%c\ %P

" enables bash aliases from vim shell
set shell=bash

" Better command-line completion
set wildmenu
set wildmode=longest,list,full
" no more pesky escape (for insert and visual mode)
imap kj <Esc>
imap kJ <Esc>
imap Kj <Esc>
imap KJ <Esc>

" better FORTRAN syntax highligthing  
let b:fortran_fixed_source=0

let g:tmuxline_powerline_separators = 1
" used patched fonts for airline arrows/triangles
let g:airline_powerline_fonts=1
"let g:airline#extensions#tabline#enabled = 1
"let g:airline#extensions#tabline#show_buffers = 0
"let g:airline#extensions#tabline#show_close_button = 0
""format the airline statusbar
let g:airline_theme='onehalfdark'


"""""""""""""""""""""""""""""""""
" Editor theme settings
"""""""""""""""""""""""""""""""""
set t_Co=256
colorscheme onehalfdark

" set Vim-specific sequences for RGB colors
if exists('+termguicolors')
    let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
    let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"
endif
"""""""""""""""""""""""""""""""""
